version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports: 
      - 27017:27017
    volumes: 
      - data:/data
    # environment: 
      # - MONGO_INITDB_ROOT_USERNAME=rootuser
      # - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
      - mongodb
  go-app:
    build: .
    container_name: go-app
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/app
    depends_on:
      - mongodb
volumes: 
  data: {} 
    
networks:
  default: 
    name: mongodb_network