###
GET http://localhost:8080/consoles/61364da771fe8e079fc3e2af HTTP/1.1

###
POST http://localhost:8080/consoles HTTP/1.1
Content-Type: application/json

{
    "name": "Xbox Series X",
    "manufacturer": "Microsoft",
    "generation": 9,
    "formfactor": "desktop console"
}

###
POST http://localhost:8080/consoles HTTP/1.1
Content-Type: application/json

{
    "name": "Playstation 5",
    "manufacturer": "Sony",
    "generation": 9,
    "formfactor": "desktop console"
}


###
POST http://localhost:8080/consoles HTTP/1.1
Content-Type: application/json

{
    "name": "Nintendo switch",
    "manufacturer": "Nintendo",
    "formfactor": "hybrid"
}

###

DELETE http://localhost:8080/consoles/61364da771fe8e079fc3e2af HTTP/1.1